// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB89ntNC9Q71rFfbnY3qS8O8YkiLeFd_WE',
    appId: '1:190658562743:web:84f84a2feac5ec03501b32',
    messagingSenderId: '190658562743',
    projectId: 'v-player-2024',
    authDomain: 'v-player-2024.firebaseapp.com',
    storageBucket: 'v-player-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCngO4C4PMTYiUa2gWxTji5UWOj8zwwryc',
    appId: '1:190658562743:android:c960cfd2cd16ac98501b32',
    messagingSenderId: '190658562743',
    projectId: 'v-player-2024',
    storageBucket: 'v-player-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFvrz9YL5sCdy6hPjFarp-IZsUy94Lzps',
    appId: '1:190658562743:ios:0a04e4aef45af7ba501b32',
    messagingSenderId: '190658562743',
    projectId: 'v-player-2024',
    storageBucket: 'v-player-2024.appspot.com',
    iosBundleId: 'com.example.videoPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFvrz9YL5sCdy6hPjFarp-IZsUy94Lzps',
    appId: '1:190658562743:ios:0a04e4aef45af7ba501b32',
    messagingSenderId: '190658562743',
    projectId: 'v-player-2024',
    storageBucket: 'v-player-2024.appspot.com',
    iosBundleId: 'com.example.videoPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB89ntNC9Q71rFfbnY3qS8O8YkiLeFd_WE',
    appId: '1:190658562743:web:36c3ca85e35f3223501b32',
    messagingSenderId: '190658562743',
    projectId: 'v-player-2024',
    authDomain: 'v-player-2024.firebaseapp.com',
    storageBucket: 'v-player-2024.appspot.com',
  );
}
